# Generated by Django 5.2 on 2025-04-08 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='content',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='title',
            new_name='topic',
        ),
    ]
