# Generated by Django 5.2 on 2025-04-08 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_rename_content_question_question_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='content',
            new_name='answer',
        ),
    ]
